name: '${name}'
version: '${version}'
main: '${main}'

authors:
  - Drak

folia-supported: true

depend:
  - BukkitOfUtils

commands:
  height:
    description: Manage a player's height.
    permission: realheight.command.height
    aliases:
      - heights
      - realheight